# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/164/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/164/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/parham/Personal/School/Saddleback/2021 Fall/CS 1D/European-Vacation"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/parham/Personal/School/Saddleback/2021 Fall/CS 1D/European-Vacation"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/164/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/164/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/parham/Personal/School/Saddleback/2021 Fall/CS 1D/European-Vacation/CMakeFiles" "/home/parham/Personal/School/Saddleback/2021 Fall/CS 1D/European-Vacation//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/parham/Personal/School/Saddleback/2021 Fall/CS 1D/European-Vacation/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named European-Vacation

# Build rule for target.
European-Vacation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 European-Vacation
.PHONY : European-Vacation

# fast build rule for target.
European-Vacation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/build
.PHONY : European-Vacation/fast

#=============================================================================
# Target rules for targets named European-Vacation_autogen

# Build rule for target.
European-Vacation_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 European-Vacation_autogen
.PHONY : European-Vacation_autogen

# fast build rule for target.
European-Vacation_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation_autogen.dir/build.make CMakeFiles/European-Vacation_autogen.dir/build
.PHONY : European-Vacation_autogen/fast

Admin/Admin.o: Admin/Admin.cpp.o
.PHONY : Admin/Admin.o

# target to build an object file
Admin/Admin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/Admin/Admin.cpp.o
.PHONY : Admin/Admin.cpp.o

Admin/Admin.i: Admin/Admin.cpp.i
.PHONY : Admin/Admin.i

# target to preprocess a source file
Admin/Admin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/Admin/Admin.cpp.i
.PHONY : Admin/Admin.cpp.i

Admin/Admin.s: Admin/Admin.cpp.s
.PHONY : Admin/Admin.s

# target to generate assembly for a file
Admin/Admin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/Admin/Admin.cpp.s
.PHONY : Admin/Admin.cpp.s

DB/Database/Database.o: DB/Database/Database.cpp.o
.PHONY : DB/Database/Database.o

# target to build an object file
DB/Database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/DB/Database/Database.cpp.o
.PHONY : DB/Database/Database.cpp.o

DB/Database/Database.i: DB/Database/Database.cpp.i
.PHONY : DB/Database/Database.i

# target to preprocess a source file
DB/Database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/DB/Database/Database.cpp.i
.PHONY : DB/Database/Database.cpp.i

DB/Database/Database.s: DB/Database/Database.cpp.s
.PHONY : DB/Database/Database.s

# target to generate assembly for a file
DB/Database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/DB/Database/Database.cpp.s
.PHONY : DB/Database/Database.cpp.s

European-Vacation_autogen/mocs_compilation.o: European-Vacation_autogen/mocs_compilation.cpp.o
.PHONY : European-Vacation_autogen/mocs_compilation.o

# target to build an object file
European-Vacation_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/European-Vacation_autogen/mocs_compilation.cpp.o
.PHONY : European-Vacation_autogen/mocs_compilation.cpp.o

European-Vacation_autogen/mocs_compilation.i: European-Vacation_autogen/mocs_compilation.cpp.i
.PHONY : European-Vacation_autogen/mocs_compilation.i

# target to preprocess a source file
European-Vacation_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/European-Vacation_autogen/mocs_compilation.cpp.i
.PHONY : European-Vacation_autogen/mocs_compilation.cpp.i

European-Vacation_autogen/mocs_compilation.s: European-Vacation_autogen/mocs_compilation.cpp.s
.PHONY : European-Vacation_autogen/mocs_compilation.s

# target to generate assembly for a file
European-Vacation_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/European-Vacation_autogen/mocs_compilation.cpp.s
.PHONY : European-Vacation_autogen/mocs_compilation.cpp.s

ManageCity/City/City.o: ManageCity/City/City.cpp.o
.PHONY : ManageCity/City/City.o

# target to build an object file
ManageCity/City/City.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/City/City.cpp.o
.PHONY : ManageCity/City/City.cpp.o

ManageCity/City/City.i: ManageCity/City/City.cpp.i
.PHONY : ManageCity/City/City.i

# target to preprocess a source file
ManageCity/City/City.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/City/City.cpp.i
.PHONY : ManageCity/City/City.cpp.i

ManageCity/City/City.s: ManageCity/City/City.cpp.s
.PHONY : ManageCity/City/City.s

# target to generate assembly for a file
ManageCity/City/City.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/City/City.cpp.s
.PHONY : ManageCity/City/City.cpp.s

ManageCity/ManageCities.o: ManageCity/ManageCities.cpp.o
.PHONY : ManageCity/ManageCities.o

# target to build an object file
ManageCity/ManageCities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/ManageCities.cpp.o
.PHONY : ManageCity/ManageCities.cpp.o

ManageCity/ManageCities.i: ManageCity/ManageCities.cpp.i
.PHONY : ManageCity/ManageCities.i

# target to preprocess a source file
ManageCity/ManageCities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/ManageCities.cpp.i
.PHONY : ManageCity/ManageCities.cpp.i

ManageCity/ManageCities.s: ManageCity/ManageCities.cpp.s
.PHONY : ManageCity/ManageCities.s

# target to generate assembly for a file
ManageCity/ManageCities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/ManageCity/ManageCities.cpp.s
.PHONY : ManageCity/ManageCities.cpp.s

UI/Map/Map.o: UI/Map/Map.cpp.o
.PHONY : UI/Map/Map.o

# target to build an object file
UI/Map/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/Map/Map.cpp.o
.PHONY : UI/Map/Map.cpp.o

UI/Map/Map.i: UI/Map/Map.cpp.i
.PHONY : UI/Map/Map.i

# target to preprocess a source file
UI/Map/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/Map/Map.cpp.i
.PHONY : UI/Map/Map.cpp.i

UI/Map/Map.s: UI/Map/Map.cpp.s
.PHONY : UI/Map/Map.s

# target to generate assembly for a file
UI/Map/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/Map/Map.cpp.s
.PHONY : UI/Map/Map.cpp.s

UI/ModdedLineEdit/moddedlineedit.o: UI/ModdedLineEdit/moddedlineedit.cpp.o
.PHONY : UI/ModdedLineEdit/moddedlineedit.o

# target to build an object file
UI/ModdedLineEdit/moddedlineedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/ModdedLineEdit/moddedlineedit.cpp.o
.PHONY : UI/ModdedLineEdit/moddedlineedit.cpp.o

UI/ModdedLineEdit/moddedlineedit.i: UI/ModdedLineEdit/moddedlineedit.cpp.i
.PHONY : UI/ModdedLineEdit/moddedlineedit.i

# target to preprocess a source file
UI/ModdedLineEdit/moddedlineedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/ModdedLineEdit/moddedlineedit.cpp.i
.PHONY : UI/ModdedLineEdit/moddedlineedit.cpp.i

UI/ModdedLineEdit/moddedlineedit.s: UI/ModdedLineEdit/moddedlineedit.cpp.s
.PHONY : UI/ModdedLineEdit/moddedlineedit.s

# target to generate assembly for a file
UI/ModdedLineEdit/moddedlineedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/ModdedLineEdit/moddedlineedit.cpp.s
.PHONY : UI/ModdedLineEdit/moddedlineedit.cpp.s

UI/login/login.o: UI/login/login.cpp.o
.PHONY : UI/login/login.o

# target to build an object file
UI/login/login.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/login/login.cpp.o
.PHONY : UI/login/login.cpp.o

UI/login/login.i: UI/login/login.cpp.i
.PHONY : UI/login/login.i

# target to preprocess a source file
UI/login/login.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/login/login.cpp.i
.PHONY : UI/login/login.cpp.i

UI/login/login.s: UI/login/login.cpp.s
.PHONY : UI/login/login.s

# target to generate assembly for a file
UI/login/login.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/UI/login/login.cpp.s
.PHONY : UI/login/login.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/European-Vacation.dir/build.make CMakeFiles/European-Vacation.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... European-Vacation_autogen"
	@echo "... European-Vacation"
	@echo "... Admin/Admin.o"
	@echo "... Admin/Admin.i"
	@echo "... Admin/Admin.s"
	@echo "... DB/Database/Database.o"
	@echo "... DB/Database/Database.i"
	@echo "... DB/Database/Database.s"
	@echo "... European-Vacation_autogen/mocs_compilation.o"
	@echo "... European-Vacation_autogen/mocs_compilation.i"
	@echo "... European-Vacation_autogen/mocs_compilation.s"
	@echo "... ManageCity/City/City.o"
	@echo "... ManageCity/City/City.i"
	@echo "... ManageCity/City/City.s"
	@echo "... ManageCity/ManageCities.o"
	@echo "... ManageCity/ManageCities.i"
	@echo "... ManageCity/ManageCities.s"
	@echo "... UI/Map/Map.o"
	@echo "... UI/Map/Map.i"
	@echo "... UI/Map/Map.s"
	@echo "... UI/ModdedLineEdit/moddedlineedit.o"
	@echo "... UI/ModdedLineEdit/moddedlineedit.i"
	@echo "... UI/ModdedLineEdit/moddedlineedit.s"
	@echo "... UI/login/login.o"
	@echo "... UI/login/login.i"
	@echo "... UI/login/login.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

