name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Update Arch and install requisite packages
        run: pacman -Syu --noconfirm --noprogressbar --needed qt6-base cmake nodejs-lts-fermium base-devel git

      - uses: actions/checkout@v2

      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          create_package: OFF

      # - name: Create tarball
      #   run: |
      #     cd build
      #     tar cvpaf $(git rev-parse --short HEAD).tar.gz European-Vacation

      - uses: actions/upload-artifact@v2
        with:
          path: build/European-Vacation
